name: webview
description: Network graph that can be embedded as a webview.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  file_picker: ^5.3.3
  flutter:
    sdk: flutter
  graphview:
    path: ../
  provider: ^6.0.3
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/network_overview/
     - assets/sample_network_configurations/
     - assets/fonts/

  fonts:
    - family: DevoloFont
      fonts:
        - asset: assets/fonts/DevoloFont.ttf # icons for barcode, checkbox, lan and wi-fi devices
        - asset: assets/fonts/devolo_iconfont_400_regular.ttf
          weight: 400
        - asset: assets/fonts/devolo_iconfont_600_semibold.ttf
          weight: 600
        - asset: assets/fonts/devolo_iconfont_700_bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans_light.ttf
          weight: 300
        - asset: assets/fonts/opensans_regular.ttf
          weight: 400
        - asset: assets/fonts/opensans_semibold.ttf
          weight: 600
        - asset: assets/fonts/opensans_bold.ttf
          weight: 700
        - asset: assets/fonts/opensans_italic.ttf
          style: italic